#ifndef CONFIG
#define CONFIG

// Communication
#define CONF_SERIAL_COM_BAUD_RATE 9600

// Timing
#define CONF_SERIAL_PORT_INIT_TIMEOUT_MS 2000
#define CONF_LED_INDICATORS_STATE_INTERVAL_MS 250
#define CONF_FREE_HEAP_MEMORY_DEBUG_LOG_INTERVAL_MS 10000
#define CONF_WIFI_NETWORKS_SCAN_INTERVAL_MS 4000
#define CONF_SENSOR_DETECTION_INTERVAL_MS 4000
#define CONF_DEBUG_FORCED_INITIALIZATION_DELAY_MS 20000
#define CONF_WIFI_AUTO_CONNECTION_TIMEOUT_MS 5000

// Bluetooth
#define CONF_DEVICE_SERVICE_UUID "19b10000-e8f2-537e-4f6c-d104768a1214"
#define CONF_DEVICE_SERVICE_CONFIGURATION_CHARACTERISTIC_UIID "19b10001-e8f2-537e-4f6c-d104768a1214"
#define CONF_DEVICE_SERVICE_SSIDS_CHARACTERISTIC_UIID "19b10001-e8f2-537e-4f6c-d104768a1213"

// Storage
#define CONF_STORAGE_NAME "STORAGE"
#define CONF_STORAGE_CLIENT_CERT_LABEL "CLIENT_CERT"
#define CONF_STORAGE_PRIVATE_KEY_LABEL "PRIVATE_KEY"
#define CONF_STORAGE_ENCRYPTION_KEY_LABEL "ENCRYPTION_KEY"

// AWS settings
#define CONF_AWS_REGION "eu-west-1"
#define CONF_AWS_IOT_CORE_ACCOUNT_IDENTIFIER "avo0w7o1tlck1"
#define CONF_AWS_ACCOUNT_ID "767398097786"

// AWS IoT Core settings
// Note: AWS IoT Core endpoint is structure as follows: <AWS IoT Core account identifier>-ats.iot.<AWS region>.amazonaws.com;
// the -ats suffix indicates that AWS IoT Core uses Amazon Trust Services (ATS) certificates for authentication.
#define CONF_AWS_IOT_CORE_ENDPOINT CONF_AWS_IOT_CORE_ACCOUNT_IDENTIFIER "-ats.iot." CONF_AWS_REGION ".amazonaws.com"
#define CONF_AWS_CERTIFICATES_PROVISIONING_TOPIC "$aws/certificates/create/json"
#define CONF_AWS_CERTIFICATES_PROVISIONING_RESPONSE_TOPIC "$aws/certificates/create/json/accepted"
#define CONF_AWS_DEVICE_PROVISIONING_TEMPLATE "museum-alert-provisioning-template"
#define CONF_AWS_DEVICE_PROVISIONING_TOPIC "$aws/provisioning-templates/" CONF_AWS_DEVICE_PROVISIONING_TEMPLATE "/provision/json"
#define CONF_AWS_DEVICE_PROVISIONING_RESPONSE_TOPIC "$aws/provisioning-templates/" CONF_AWS_DEVICE_PROVISIONING_TEMPLATE "/provision/json/accepted"
#define CONF_DEVICE_INCOMING_COMMANDS_TOPIC_TEMPLATE "arn:aws:iot:" CONF_AWS_REGION ":" CONF_AWS_ACCOUNT_ID ":topic/%s/sub"
#define CONF_DEVICE_OUTGOING_DATA_TOPIC_TEMPLATE "arn:aws:iot:" CONF_AWS_REGION ":" CONF_AWS_ACCOUNT_ID ":topic/%s/pub"

#endif
