name: Arduino Sketch CI

on:
  push:
    branches: [ main, improvements ]
  pull_request:
    branches: [ main, improvements ]

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      
    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:esp32@2.0.18
        
    - name: List available boards
      run: |
        echo "Available Arduino ESP32 boards:"
        arduino-cli board listall arduino:esp32
        
    - name: Install required libraries
      run: |
        arduino-cli lib install "ArduinoJson@7.4.2"
        arduino-cli lib install "PubSubClient@2.8"
        
    - name: List directory structure
      run: |
        echo "Current working directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Source files:"
        find . -name "*.ino" -o -name "*.h" -o -name "*.cpp" | head -20
        
    - name: Verify config setup
      run: |
        echo "Checking config.h for RELEASE_BUILD conditional:"
        grep -A 3 -B 1 "RELEASE_BUILD" config.h || echo "RELEASE_BUILD conditional not found"
        
    - name: Compile sketch
      run: |
        echo "Starting compilation of museum-alert-sketch..."
        echo "Using Arduino ESP32 Nano board target (arduino:esp32:nano_nora)..."
        echo "Building in RELEASE mode (DEBUG disabled via -DRELEASE_BUILD)..."
        arduino-cli compile --fqbn arduino:esp32:nano_nora --build-property build.extra_flags=-DRELEASE_BUILD museum-alert-sketch.ino --verbose --output-dir ./build
        echo "Compilation completed successfully!"
        
    - name: Display build output info
      run: |
        echo "Build artifacts created:"
        find ./build -name "*.bin" -o -name "*.elf" -o -name "*.hex" | head -10
        
    - name: Upload compilation artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: compilation-output
        path: |
          ./build/
        retention-days: 7
